"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REPETITION_LIMIT = exports.MAX_HINTS_PER_GAME = exports.DEFAULT_HINTS_PER_GAME = exports.FIFTY_MOVE_LIMIT = exports.PERPETUAL_LIMIT = exports.COL_TO_FILE = exports.FILE_MAP = exports.RANKS = exports.FILES = exports.RIVER_BLACK_SIDE_END = exports.RIVER_RED_SIDE_START = exports.PALACE_COL_END = exports.PALACE_COL_START = exports.BLACK_PALACE_ROW_END = exports.BLACK_PALACE_ROW_START = exports.RED_PALACE_ROW_END = exports.RED_PALACE_ROW_START = exports.BOARD_CELL_COUNT = void 0;
var board_constants_1 = require("./board.constants");
Object.defineProperty(exports, "BOARD_CELL_COUNT", { enumerable: true, get: function () { return board_constants_1.BOARD_CELL_COUNT; } });
Object.defineProperty(exports, "RED_PALACE_ROW_START", { enumerable: true, get: function () { return board_constants_1.RED_PALACE_ROW_START; } });
Object.defineProperty(exports, "RED_PALACE_ROW_END", { enumerable: true, get: function () { return board_constants_1.RED_PALACE_ROW_END; } });
Object.defineProperty(exports, "BLACK_PALACE_ROW_START", { enumerable: true, get: function () { return board_constants_1.BLACK_PALACE_ROW_START; } });
Object.defineProperty(exports, "BLACK_PALACE_ROW_END", { enumerable: true, get: function () { return board_constants_1.BLACK_PALACE_ROW_END; } });
Object.defineProperty(exports, "PALACE_COL_START", { enumerable: true, get: function () { return board_constants_1.PALACE_COL_START; } });
Object.defineProperty(exports, "PALACE_COL_END", { enumerable: true, get: function () { return board_constants_1.PALACE_COL_END; } });
Object.defineProperty(exports, "RIVER_RED_SIDE_START", { enumerable: true, get: function () { return board_constants_1.RIVER_RED_SIDE_START; } });
Object.defineProperty(exports, "RIVER_BLACK_SIDE_END", { enumerable: true, get: function () { return board_constants_1.RIVER_BLACK_SIDE_END; } });
Object.defineProperty(exports, "FILES", { enumerable: true, get: function () { return board_constants_1.FILES; } });
Object.defineProperty(exports, "RANKS", { enumerable: true, get: function () { return board_constants_1.RANKS; } });
Object.defineProperty(exports, "FILE_MAP", { enumerable: true, get: function () { return board_constants_1.FILE_MAP; } });
Object.defineProperty(exports, "COL_TO_FILE", { enumerable: true, get: function () { return board_constants_1.COL_TO_FILE; } });
var thresholds_constants_1 = require("./thresholds.constants");
Object.defineProperty(exports, "PERPETUAL_LIMIT", { enumerable: true, get: function () { return thresholds_constants_1.PERPETUAL_LIMIT; } });
Object.defineProperty(exports, "FIFTY_MOVE_LIMIT", { enumerable: true, get: function () { return thresholds_constants_1.FIFTY_MOVE_LIMIT; } });
Object.defineProperty(exports, "DEFAULT_HINTS_PER_GAME", { enumerable: true, get: function () { return thresholds_constants_1.DEFAULT_HINTS_PER_GAME; } });
Object.defineProperty(exports, "MAX_HINTS_PER_GAME", { enumerable: true, get: function () { return thresholds_constants_1.MAX_HINTS_PER_GAME; } });
Object.defineProperty(exports, "REPETITION_LIMIT", { enumerable: true, get: function () { return thresholds_constants_1.REPETITION_LIMIT; } });
//# sourceMappingURL=index.js.map