"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_THRESHOLDS = exports.MoveClassification = exports.DIFFICULTY_MOVETIME = exports.STARTING_FEN = exports.BOARD_SIZE = exports.BOARD_ROWS = exports.BOARD_COLS = exports.PIECE_CHARS = exports.PIECE_CODE_TO_FEN = exports.FEN_PIECE_MAP = exports.PieceCode = exports.Color = exports.PieceType = void 0;
var pieces_types_1 = require("./pieces.types");
Object.defineProperty(exports, "PieceType", { enumerable: true, get: function () { return pieces_types_1.PieceType; } });
Object.defineProperty(exports, "Color", { enumerable: true, get: function () { return pieces_types_1.Color; } });
Object.defineProperty(exports, "PieceCode", { enumerable: true, get: function () { return pieces_types_1.PieceCode; } });
Object.defineProperty(exports, "FEN_PIECE_MAP", { enumerable: true, get: function () { return pieces_types_1.FEN_PIECE_MAP; } });
Object.defineProperty(exports, "PIECE_CODE_TO_FEN", { enumerable: true, get: function () { return pieces_types_1.PIECE_CODE_TO_FEN; } });
Object.defineProperty(exports, "PIECE_CHARS", { enumerable: true, get: function () { return pieces_types_1.PIECE_CHARS; } });
var board_types_1 = require("./board.types");
Object.defineProperty(exports, "BOARD_COLS", { enumerable: true, get: function () { return board_types_1.BOARD_COLS; } });
Object.defineProperty(exports, "BOARD_ROWS", { enumerable: true, get: function () { return board_types_1.BOARD_ROWS; } });
Object.defineProperty(exports, "BOARD_SIZE", { enumerable: true, get: function () { return board_types_1.BOARD_SIZE; } });
Object.defineProperty(exports, "STARTING_FEN", { enumerable: true, get: function () { return board_types_1.STARTING_FEN; } });
var game_types_1 = require("./game.types");
Object.defineProperty(exports, "DIFFICULTY_MOVETIME", { enumerable: true, get: function () { return game_types_1.DIFFICULTY_MOVETIME; } });
var analysis_types_1 = require("./analysis.types");
Object.defineProperty(exports, "MoveClassification", { enumerable: true, get: function () { return analysis_types_1.MoveClassification; } });
Object.defineProperty(exports, "DEFAULT_THRESHOLDS", { enumerable: true, get: function () { return analysis_types_1.DEFAULT_THRESHOLDS; } });
//# sourceMappingURL=index.js.map